/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author class12
 */
public class booking extends javax.swing.JFrame {
    double carprice;
     String start;
    String end;
    String email1;
    /**
     * Creates new form booking
     */
    public booking(String emailID) {
        initComponents();
        this.email1=emailID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mercedes = new javax.swing.JRadioButton();
        cb1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox<>();
        bmw = new javax.swing.JRadioButton();
        audi = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(789, 525));
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 440, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pickup Address :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 114, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Drop-Off Address :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 180, 210, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 440, 92, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Select Car :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 240, 110, 20);

        buttonGroup1.add(mercedes);
        mercedes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        mercedes.setText("Mercedes");
        mercedes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mercedesItemStateChanged(evt);
            }
        });
        mercedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercedesActionPerformed(evt);
            }
        });
        getContentPane().add(mercedes);
        mercedes.setBounds(100, 290, 100, 29);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjara Hills", "Madhapur", "Gachibowli", "Jubilee Hills", "Kondapur", " " }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(470, 120, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BOOKING DETAILS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 0, 230, 53);

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjara Hills", "Madhapur\t", "Gachibowli", "Jubilee Hills", "Kondapur", " ", " " }));
        getContentPane().add(cb2);
        cb2.setBounds(470, 190, 120, 20);

        buttonGroup1.add(bmw);
        bmw.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bmw.setText("BMW");
        bmw.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bmwItemStateChanged(evt);
            }
        });
        getContentPane().add(bmw);
        bmw.setBounds(330, 290, 100, 29);

        buttonGroup1.add(audi);
        audi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        audi.setText("Audi");
        audi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                audiItemStateChanged(evt);
            }
        });
        getContentPane().add(audi);
        audi.setBounds(550, 290, 100, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipproj/images/merc.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 320, 100, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipproj/images/BMW.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 320, 100, 100);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipproj/images/audi.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(550, 320, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipproj/images/taxi_2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     start=cb1.getSelectedItem().toString().trim();  // TODO add your handling code here:
       end=cb2.getSelectedItem().toString().trim(); 
       if (start.equals(end)){
           JOptionPane.showMessageDialog(null,"Please select different pickup and dropoff location");
           
       }
       else if(mercedes.isSelected()== false && bmw.isSelected()== false && audi.isSelected()== false)
       { JOptionPane.showMessageDialog(null,"Please select a car");
               }
       else{  
           System.out.println(email1);
       map mp=new map(String.valueOf(carprice),start,end,email1);
       mp.setVisible(true);
      //mp.main(new String[]{String.valueOf(carprice),start,end});
      
       this.dispose();
       }  
       
      
       
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new loginform().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mercedesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mercedesItemStateChanged
         if(mercedes.isSelected())
       {
           carprice=1.25*40;
       }
    }//GEN-LAST:event_mercedesItemStateChanged

    private void bmwItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bmwItemStateChanged
       if(bmw.isSelected())
       {
           carprice=1.5*40;
       }
    }//GEN-LAST:event_bmwItemStateChanged

    private void audiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_audiItemStateChanged
        if(audi.isSelected())
       {
           carprice=40;
       }
    }//GEN-LAST:event_audiItemStateChanged

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void mercedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercedesActionPerformed

    }//GEN-LAST:event_mercedesActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new booking().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton audi;
    private javax.swing.JRadioButton bmw;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton mercedes;
    // End of variables declaration//GEN-END:variables
}
